### Add new element to fetch
POST localhost:8080/api/elements
Content-Type: application/json

{
  "url": "http://example.com",
  "selector": "h1"
}

### Find element by id
GET localhost:8080/api/elements/{{$random.uuid}}
Accept: application/json