services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: mysqladmin ping --protocol tcp
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s
volumes:
  mysqldb: